- name: Check if user is already in docker group
  tags: 
    - pre-docker
  ansible.builtin.shell:
    cmd: "getent group | grep docker | grep -w {{ ansible_user }}"
  register: check_docker_membership
  ignore_errors: true

- name: Add user to docker group
  tags: 
    - pre-docker
  ansible.builtin.shell:
    cmd: "usermod -aG docker {{ ansible_user }}"
  when: check_docker_membership.rc != 0

- name: Reboot the system
  tags: 
    - pre-docker
  ansible.builtin.shell:
    cmd: "reboot"
  when: check_docker_membership.rc != 0
    The 'reboot' command will disconnect the SSH connection,
    so this playbook will not continue running after this task
  async: 0
  poll: 0
