import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: "Full stack",
    template: "%s | fullstack",
    absolute: ""
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'lightblue',
            padding: "1rem"
          }}
        >
          <Link href="/">
            <p>Header</p>
          </Link>
        </header>  
        {children}
      <footer>
        <p
          style={{
            backgroundColor: 'lightblue',
            padding: "1rem"
          }}
        >Footer</p>
      </footer>
      </body>
    </html>
  )
}
