version: "3.8"
services:
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: