- name: Add user to virtual machine
  hosts: all
  become: yes
  tasks:
    - name: create automator user
      tags: always
      user: 
        name: automator
        groups: root

    
- name: Add SSH key + sudoer
  hosts: all
  become: yes
  vars:
    ssh_key_path: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
  roles:
    - base
    - add_sudoer