- name: Add user to virtual machine
  hosts: all
  become: yes
  tasks:
    - name: create automator user
      tags: always
      user: 
        name: automator
        groups: root

    - name: Add SSH key to automator user
      tags: always
      authorized_key:
        user: automator
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILUXgG6bi4Qk3IYQI1eDcOrOzGWwZUwMwshdsXwRtHA0 ansible"

    - name: add sudoers file for "automator"
      tags: always
      copy: 
        src: sudoer_automator
        dest: /etc/sudoers.d/automator
        owner: root
        group: root
        mode: 0440