---
- name: Install Caddy
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - debian-keyring
        - debian-archive-keyring
        - apt-transport-https
        - curl

    - name: Add Caddy GPG key
      shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

    - name: Add Caddy repository
      shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Caddy
      apt:
        name: caddy
        state: present

# ansible-playbook --ask-become-pass install_caddy.yml